//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace the_facts.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Joke
    {
        public Joke()
        {
            this.Categories = new HashSet<Category>();
        }
    
        public int JokeId { get; set; }
        public string JokeText { get; set; }
    
        public virtual ICollection<Category> Categories { get; set; }
    }
}
